# Generated by Django 3.0.7 on 2020-06-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truecaller', '0002_auto_20200604_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='spam',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='spam',
        ),
    ]
