# Generated by Django 3.0.7 on 2020-06-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truecaller', '0003_auto_20200604_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
